parameters:
#    lufinca.example.class: Dioptra\LufincaBundle\Example

services:
#    lufinca.example:
#        class: %lufinca.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
